# Generated by Django 4.1.3 on 2022-11-27 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_application_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_allotted',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 10, 15, 584658)),
        ),
        migrations.DeleteModel(
            name='SlotBooking',
        ),
    ]
