# Generated by Django 4.1.3 on 2022-11-27 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_application_date_allotted_delete_slotbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_allotted',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 17, 25, 845801)),
        ),
    ]
