# Generated by Django 4.1.3 on 2022-11-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_application_date_allotted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_allotted',
            field=models.DateField(blank=True, default='2022-01-01'),
        ),
    ]
